# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-30 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputform',
            name='output_parser',
            field=models.CharField(default=b'default.html', max_length=64),
        ),
    ]
