# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-31 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_forms', '0002_inputform_output_parser'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFormTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('input_forms', models.ManyToManyField(to='input_forms.InputForm')),
            ],
        ),
    ]
