# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('input_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('layout', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('input_forms', models.ManyToManyField(to='input_forms.InputForm')),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
            },
        ),
    ]
