# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='theme',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
