# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_screen_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('configuration', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ScreenWidget',
                'verbose_name_plural': 'ScreenWidgets',
            },
        ),
        migrations.AddField(
            model_name='screen',
            name='screen_widgets',
            field=models.ManyToManyField(to='screens.ScreenWidget'),
        ),
    ]
