# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0003_auto_20170327_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenWidgetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('data', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ScreenWidgetData',
                'verbose_name_plural': 'ScreenWidgetData',
            },
        ),
    ]
