# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0004_screenwidgetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenWidgetConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(max_length=64)),
                ('data', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ScreenWidgetConfig',
                'verbose_name_plural': 'ScreenWidgetConfig',
            },
        ),
    ]
