# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0007_screen_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='labels',
            field=models.ManyToManyField(to='screens.ScreenLabels'),
        ),
    ]
