from django.conf.urls import url

from input_forms import views


urlpatterns = [
    url(r"^$", views.index,
        name="index"),
    url(r"^create$", views.create,
        name="create"),
    url(r"^update", views.update,
        name="update"),
    url(r"^search$", views.search,
        name="search"),
    url(r"^searchAll$", views.search_all,
        name="search_all"),
    url(r"^searchMulti$", views.search_multi,
        name="search_multi"),
    url(r"^searchTags$", views.search_tags,
        name="search_tags"),
    url(r"^searchForm$", views.search_form,
        name="search_form"),
    url(r"^searchStandalone$", views.search_standalone,
        name="search_standalone"),
    url(r"^preview/(?P<input_form_id>[0-9]+)/$", views.preview,
        name="preview"),
    url(r"^configureTemplate$", views.configure_template_for_endpoint,
        name="configure_template_for_endpoint"),
    url(r"^configureTemplateForQueue", views.configure_template_for_queue,
        name="configure_template_for_queue"),
    url(r"^configureTemplateForScreen/(?P<input_form_id>[0-9]+)", views.configure_template_for_screen,
        name="configure_template_for_screen"),
    url(r"^apply$", views.apply_per_endpoint_template,
        name="apply_per_endpoint_template"),
    url(r"^applyToQueue", views.apply_template_to_queue,
        name="apply_template_to_queue"),
    url(r"^applyStandalone$", views.apply_standalone_template,
        name="apply_standalone_template"),
    url(r"^edit/(?P<input_form_id>[0-9]+)/$", views.edit,
        name="edit"),
    url(r"^delete/(?P<input_form_id>[0-9]+)/$", views.delete,
        name="delete"),
    url(r"^(?P<input_form_id>[0-9]+)$", views.detail,
        name="details"),
    url(r"^export/(?P<input_form_id>[^/]+)$", views.export_form,
        name="export_form"),
    url(r"^import/$", views.import_form,
        name="import_form"),
    url(r"^new/(?P<template_id>[0-9]+)$", views.new_from_template,
        name="new_from_template"),
    url(r"^view_from_template/(?P<template_id>[0-9]+)/$", views.view_from_template,
        name="view_from_template"),
    url(r"^edit_from_template/(?P<template_id>[0-9]+)/$", views.edit_from_template,
        name="edit_from_template"),
    url(r"^loadWidgetConfig/$", views.load_widget_config,
        name="load_widget_config"),
    url(r"^loadTagEditor/$", views.load_tag_editor,
        name="load_tag_editor"),
    url(r"^configureTags$", views.configure_tags,
        name="configure_tags"),
]
