# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('template', models.TextField()),
                ('action_provider', models.CharField(max_length=64)),
                ('action_provider_options', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[(b'standalone', b'Standalone'), (b'per-endpoint', b'Per-Endpoint')], default=b'standalone', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ConfigTemplate',
                'verbose_name_plural': 'configTemplates',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('script', models.TextField()),
                ('type', models.CharField(choices=[(b'ssh', b'On-Box'), (b'netconf', b'Off-Box')], default=b'netconf', max_length=32)),
                ('destination', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'script',
                'verbose_name_plural': 'scripts',
            },
        ),
    ]
